[package]
name = "cat-vg"
version = "0.1.0"
authors = ["win"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl-graphic = {path="../gl-graphic"}
graphic-core = {path="../graphic-core"}
